// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrungTamQuanLiDT.Data;

#nullable disable

namespace TrungTamQuanLiDT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250423163827_MiniUpdate")]
    partial class MiniUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrungTamQuanLiDT.Models.DangKyKhoaHocModel", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("DangKyHocs");
                });

            modelBuilder.Entity("TrungTamQuanLiDT.Models.KhoaHocModel", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("GiangVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HocPhi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SoLuongHocVienToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKhaiGiang")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KhoaHocs");

                    b.HasData(
                        new
                        {
                            MaKhoaHoc = 1,
                            GiangVien = "Nguyễn Văn A",
                            HocPhi = 2500000m,
                            SoLuongHocVienToiDa = 30,
                            TenKhoaHoc = "Lập trình C# cơ bản",
                            ThoiGianKetThuc = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhaiGiang = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaKhoaHoc = 2,
                            GiangVien = "Trần Thị B",
                            HocPhi = 3200000m,
                            SoLuongHocVienToiDa = 25,
                            TenKhoaHoc = "ASP.NET Core MVC nâng cao",
                            ThoiGianKetThuc = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhaiGiang = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaKhoaHoc = 3,
                            GiangVien = "Lê Văn C",
                            HocPhi = 2700000m,
                            SoLuongHocVienToiDa = 35,
                            TenKhoaHoc = "Cơ sở dữ liệu với SQL Server",
                            ThoiGianKetThuc = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhaiGiang = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaKhoaHoc = 4,
                            GiangVien = "Phạm Thị D",
                            HocPhi = 5000000m,
                            SoLuongHocVienToiDa = 20,
                            TenKhoaHoc = "Phát triển Web Fullstack",
                            ThoiGianKetThuc = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhaiGiang = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaKhoaHoc = 5,
                            GiangVien = "Hoàng Văn E",
                            HocPhi = 1800000m,
                            SoLuongHocVienToiDa = 40,
                            TenKhoaHoc = "Thiết kế giao diện với HTML/CSS",
                            ThoiGianKetThuc = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhaiGiang = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaKhoaHoc = 6,
                            GiangVien = "Đặng Thị F",
                            HocPhi = 2600000m,
                            SoLuongHocVienToiDa = 30,
                            TenKhoaHoc = "Lập trình Python cơ bản",
                            ThoiGianKetThuc = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhaiGiang = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaKhoaHoc = 7,
                            GiangVien = "Bùi Văn G",
                            HocPhi = 2900000m,
                            SoLuongHocVienToiDa = 25,
                            TenKhoaHoc = "Kỹ thuật phân tích hệ thống",
                            ThoiGianKetThuc = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKhaiGiang = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TrungTamQuanLiDT.Models.UserModel", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHocVien");

                    b.HasIndex("TaiKhoan")
                        .IsUnique();

                    b.ToTable("HocViens");

                    b.HasData(
                        new
                        {
                            MaHocVien = 1,
                            Email = "a@gmail.com",
                            HoTen = "Nguyen Van A",
                            MatKhau = "Aa123456!",
                            NgaySinh = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000001",
                            TaiKhoan = "nguyenvana"
                        },
                        new
                        {
                            MaHocVien = 2,
                            Email = "b@gmail.com",
                            HoTen = "Tran Thi B",
                            MatKhau = "Bb987654@",
                            NgaySinh = new DateTime(2000, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000002",
                            TaiKhoan = "tranthib"
                        },
                        new
                        {
                            MaHocVien = 3,
                            Email = "c@gmail.com",
                            HoTen = "Le Van C",
                            MatKhau = "Cc456789#",
                            NgaySinh = new DateTime(2000, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000003",
                            TaiKhoan = "levanc"
                        },
                        new
                        {
                            MaHocVien = 4,
                            Email = "d@gmail.com",
                            HoTen = "Pham Thi D",
                            MatKhau = "Dd654321$",
                            NgaySinh = new DateTime(2000, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000004",
                            TaiKhoan = "phamthid"
                        },
                        new
                        {
                            MaHocVien = 5,
                            Email = "e@gmail.com",
                            HoTen = "Hoang Van E",
                            MatKhau = "Ee112233%",
                            NgaySinh = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000005",
                            TaiKhoan = "hoangvane"
                        },
                        new
                        {
                            MaHocVien = 6,
                            Email = "f@gmail.com",
                            HoTen = "Dang Thi F",
                            MatKhau = "Ff445566^",
                            NgaySinh = new DateTime(2000, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000006",
                            TaiKhoan = "dangthif"
                        },
                        new
                        {
                            MaHocVien = 7,
                            Email = "g@gmail.com",
                            HoTen = "Bui Van G",
                            MatKhau = "Gg778899&",
                            NgaySinh = new DateTime(2000, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000007",
                            TaiKhoan = "buivang"
                        },
                        new
                        {
                            MaHocVien = 8,
                            Email = "h@gmail.com",
                            HoTen = "Do Thi H",
                            MatKhau = "Hh990011*",
                            NgaySinh = new DateTime(2000, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000008",
                            TaiKhoan = "dothih"
                        },
                        new
                        {
                            MaHocVien = 9,
                            Email = "i@gmail.com",
                            HoTen = "Nguyen Van I",
                            MatKhau = "Ii334455(",
                            NgaySinh = new DateTime(2000, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000009",
                            TaiKhoan = "nguyenvani"
                        },
                        new
                        {
                            MaHocVien = 10,
                            Email = "j@gmail.com",
                            HoTen = "Tran Thi J",
                            MatKhau = "Jj667788)",
                            NgaySinh = new DateTime(2000, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1,
                            SDT = "0901000010",
                            TaiKhoan = "tranthij"
                        },
                        new
                        {
                            MaHocVien = 11,
                            Email = "admin1@domain.com",
                            HoTen = "Admin One",
                            MatKhau = "Admin@123",
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0,
                            SDT = "0902000001",
                            TaiKhoan = "admin1"
                        },
                        new
                        {
                            MaHocVien = 12,
                            Email = "admin2@domain.com",
                            HoTen = "Admin Two",
                            MatKhau = "Admin#456",
                            NgaySinh = new DateTime(1990, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0,
                            SDT = "0902000002",
                            TaiKhoan = "admin2"
                        });
                });

            modelBuilder.Entity("TrungTamQuanLiDT.ViewModel.LoginViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("TrungTamQuanLiDT.Models.DangKyKhoaHocModel", b =>
                {
                    b.HasOne("TrungTamQuanLiDT.Models.UserModel", "HocVien")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrungTamQuanLiDT.Models.KhoaHocModel", "KhoaHoc")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("TrungTamQuanLiDT.Models.KhoaHocModel", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("TrungTamQuanLiDT.Models.UserModel", b =>
                {
                    b.Navigation("DangKyHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
